### ISSUE TITLE
Arcade core: CosmicAvenger.rbf: Can't drop bombs

### ISSUE THREAD

**Issue by NML32** [Gehstock/Mist_Cores#1]
I'm not sure if the second fire button for dropping bombs has been mapped.
Also, the game starts on bootup no coins needed.

**Comment by Gehstock** [comment]
Problem is somewhere in the Logic, Mappings are correct, have same Problem in Asteroids (Warp-Function) and other Games. Pace Framework have an Issue with the Mappings.

**Comment by NML32** [comment]
Thanks for the quick coin fix. The other issue sounds tricky I hope you can find a solution.

**Comment by Gehstock** [comment]
Bombs mapped to Fire Button. Will be fixed later

**Comment by NML32** [comment]
@Gehstock thanks, this seems like a great work-around until you can figure out how to map bombs to the second fire button.

**Comment by Gehstock** [comment]
Finally Fixed
